# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c485131e0ec7c68b856df6a73f69f350fe191062de185babcd4e09d7bb3be86091fa16058046508c71072a9ac7692142a0cde2e33ca5d0b89dc9e4ea2b274aa

test:
  secret_key_base: e94ae6999611e598fa2c388df299ce13095c96623c71cdbaab39987e287168147214fbde81c5cebc7c42f52a32171311c6a0fe512a0a3be46cb59eba33c788f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
